import {
  mdiAccount,
  mdiBeer,
  mdiCalendar,
  mdiCamera,
  mdiCardAccountDetails,
  mdiCart,
  mdiCoffee,
  mdiEmail,
  mdiGift,
  mdiGlassCocktail,
  mdiGlassWine,
  mdiHeart,
  mdiHome,
  mdiLink,
  mdiMapMarker,
  mdiMessageText,
  mdiMusic,
  mdiPaw,
  mdiPhone,
  mdiShareVariant,
  mdiSilverware,
  mdiStar,
  mdiStore,
  mdiWeb,
  mdiWifi,
} from '@mdi/js';
import {
  siAppstore,
  siBitcoin,
  siBluesky,
  siBuymeacoffee,
  siCashapp,
  siDiscord,
  siEtsy,
  siFacebook,
  siGithub,
  siGoogleplay,
  siInstagram,
  siKofi,
  siLinktree,
  siMastodon,
  siPatreon,
  siPaypal,
  siPinterest,
  siReddit,
  siSignal,
  siSnapchat,
  siSoundcloud,
  siSpotify,
  siStrava,
  siTelegram,
  siThreads,
  siTiktok,
  siTwitch,
  siUntappd,
  siVenmo,
  siWhatsapp,
  siX,
  siYelp,
  siYoutube,
  type SimpleIcon,
} from 'simple-icons';
import { artFromItems, svgPathToCommands, type LogoArt } from './art';

export interface Icon {
  id: string;
  label: string;
  path: string;
  group: 'general' | 'brand';
}

const general = (id: string, label: string, path: string): Icon => ({ id, label, path, group: 'general' });
const brand = (icon: SimpleIcon): Icon => ({ id: icon.slug, label: icon.title, path: icon.path, group: 'brand' });

export const ICONS: Icon[] = [
  general('wifi', 'Wi-Fi', mdiWifi),
  general('link', 'Link', mdiLink),
  general('web', 'Website', mdiWeb),
  general('email', 'Email', mdiEmail),
  general('phone', 'Phone', mdiPhone),
  general('message', 'Message', mdiMessageText),
  general('contact', 'Contact card', mdiCardAccountDetails),
  general('person', 'Person', mdiAccount),
  general('calendar', 'Calendar', mdiCalendar),
  general('location', 'Location', mdiMapMarker),
  general('share', 'Share', mdiShareVariant),
  general('home', 'Home', mdiHome),
  general('store', 'Store', mdiStore),
  general('cart', 'Cart', mdiCart),
  general('coffee', 'Coffee', mdiCoffee),
  general('beer', 'Beer', mdiBeer),
  general('wine', 'Wine', mdiGlassWine),
  general('cocktail', 'Cocktail', mdiGlassCocktail),
  general('dining', 'Dining', mdiSilverware),
  general('music', 'Music', mdiMusic),
  general('camera', 'Camera', mdiCamera),
  general('gift', 'Gift', mdiGift),
  general('heart', 'Heart', mdiHeart),
  general('star', 'Star', mdiStar),
  general('paw', 'Paw', mdiPaw),
  ...[
    siFacebook,
    siInstagram,
    siX,
    siThreads,
    siBluesky,
    siMastodon,
    siTiktok,
    siYoutube,
    siTwitch,
    siDiscord,
    siReddit,
    siPinterest,
    siSnapchat,
    siWhatsapp,
    siTelegram,
    siSignal,
    siSpotify,
    siSoundcloud,
    siGithub,
    siPatreon,
    siKofi,
    siBuymeacoffee,
    siLinktree,
    siVenmo,
    siPaypal,
    siCashapp,
    siBitcoin,
    siEtsy,
    siYelp,
    siUntappd,
    siStrava,
    siAppstore,
    siGoogleplay,
  ].map(brand),
];

export function findIcon(id: string): Icon | undefined {
  return ICONS.find((icon) => icon.id === id);
}

export function iconArt(icon: Icon): LogoArt | null {
  return artFromItems([{ color: '#000000', commands: svgPathToCommands(icon.path) }]);
}
